### ISSUE TITLE
Not Logging correct time

### ISSUE THREAD

**Issue by 1sdc0d3r** [swdotcom/swdc-vscode#60] opened 2019-10-17 19:38 UTC
After multiple hours and hours of coding, It says that I have only coded a few hours. It is not staying accurate with the time that I have coded. This is very important to me.

**Comment by abz89** [comment] 2019-10-21 12:25
> After multiple hours and hours of coding, It says that I have only coded a few hours. It is not staying accurate with the time that I have coded. This is very important to me.

Yup me too! After coding by hours, the extension only show some minutes!
Since then i always (most of time) look at the 'timer' while coding, the 'timer' seems randomly reset to 0 after a few minutes.

Please fix this issue cause this extension is very helpful for me,
Thank's for nice extension

**Comment by evan-kapantais** [comment] 2019-10-25 18:28
Yup, happens to me also. Time logging is the core function of the extension and this needs to be fixed asap.

**Comment by ethanbrooks** [comment] 2019-10-26 11:32
I think it maybe an issue with having multiple VS code windows open as my timer just keep reseting to 0.

Great idea, to introspect the IDE for hours, impressive IDE support... Impossibly amazing domain domain name.. but, doesn't work.

**Comment by evan-kapantais** [comment] 2019-10-26 15:56
Nope, I always have just one instance open and now keeps happening every day. Quite frustrating.

**Comment by nditanaka** [comment] 2019-10-27 00:47
@evan-kapantais  I am facing the same issue as well! It keeps randomly resetting to a very small number of minutes.

**Comment by andrewhli** [comment] 2019-10-27 00:51
Hi everyone, I've very sorry about this serious bug in Code Time. Fixing it is our top priority for the next 3 days, and I'll work with the team to ensure that it works as everyone expects. To fully understand the problem that you're seeing, is the Code Time counter in the VS Code status bar accumulating time, then resetting to 0 or a very small number? Has there been any pattern to the reset (for example, after 15 minutes of inactivity in VS Code)? We'll get this fixed.

**Comment by nditanaka** [comment] 2019-10-27 02:45
Thank you for working on this! The time counter in the VS code status bar is accumulating time then resetting to 0 or a small number like 1 or 3 minutes. It might be after a brief period of inactivity, but I am not sure. I have seen it go up to 19 minutes, but never to a number above 20 minutes.

**Comment by abz89** [comment] 2019-10-27 04:22
Thank you for prioritising this bug. Yup the status bar counter keep resetting after small number of minutes but never above 15-20 minutes whether VS Code active/not, and I can confirm that multiple instances (both same or different repos) is working well before.

**Comment by andrewhli** [comment] 2019-10-29 00:15
Hi @1sdc0d3r @evan-kapantais @ethanbrooks @abz89 @nditanaka - The team has pushed a fix for this issue in the latest version of Code Time in v1.1.32 (https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode). 

I've tested this version personally and have gotten my code time tracker for the day to 1.6 hours, so it should no longer reset after 30 minutes.

If you see any other issues, please let us know, and we'll make it a priority.

**Comment by evan-kapantais** [comment] 2019-10-29 11:31
Thanks for the swift update Andrew

**Comment by andrewhli** [comment] 2019-10-30 03:02
Hi @1sdc0d3r @evan-kapantais @ethanbrooks @abz89 @nditanaka - Thanks again for your help alerting us of this bug, and it sounds like everything's working as expected. We have a small Slack community for our power users to communicate feature requests directly to us and alert us of bugs immediately after they're spotted. Hope to see you there! Here's the link:
 
https://join.slack.com/t/software-community/shared_invite/enQtNzA4NjI4MDI4NTQ0LTQ0Mjc4NDBiNDhkN2M3NjUwYmNmYWUwMjI5MGRmZjUwNzFlYjM2NDFlMGIwMmJmODNhNTU3ZGVjZmNlZGVjMmE

**Closed by andrewhli** 2019-10-30 03:02 UTC
Labels: bug
