### ISSUE TITLE
Projects not listing

### ISSUE THREAD

**Issue by mister-gnommer** [swdotcom/swdc-vscode#174] opened 2020-11-30 19:19 UTC
**Describe the bug**
```paste below
When trying to see project summary I see only empty input box with "Select one or more projects" with no projects listed.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open VS Code
2. Click "View project summary"
3. See empty list ;)

**Screenshots**

![image](https://user-images.githubusercontent.com/61603428/100653387-9b3c1500-3348-11eb-9479-c398778f1ca3.png)

**Desktop (please complete the following information):**
 - OS: win10 Pro 64
 - Plugin version: 2.3.21
 - VS code: 1.51.1

**Additional context**
```paste below
Problem seems to be same as in #133 , but in my case it was working some time ago. Can't say when it got broken, I'm not using it too often.
Tried to reinstall plugin, didn't help. I'm using git repositories to track projects.
```

**Comment by mmclead** [comment] 2020-11-30 20:21
@mister-gnommer Thank you reporting the issue.  I'm sorry that it's not working as it should.  
We are looking into it right away.

**Comment by mmclead** [comment] 2020-11-30 23:01
Update:   All of your data is safe and secure.   I do see that we have it all there.    The issue is that we've been deprecating older APIs and this one got caught up in it.   We'll be pushing updates soon to get this feature back online for you and everyone else.

**Comment by mmclead** [comment] 2020-12-01 22:40
@mister-gnommer the fix for this is live and you're projects should all be listed in the Editor views now.   Also, you should be able to see all of it in the web dashboard.    

Please let me know if you're all set now.   Thanks again for reporting the issue.

**Comment by mister-gnommer** [comment] 2020-12-02 22:02
@mmclead at first thank for your commitment, your react is more professional then in many paid services, great thing, really! ;)
But... it still doesn't work. Projects are listing now, but they are multiplied and after choosing any I still don't get report.
![image](https://user-images.githubusercontent.com/61603428/100936858-6d92cf80-34f2-11eb-95f6-6488d5e00fc0.png)

**Comment by mmclead** [comment] 2020-12-02 23:58
Happy to help @mister-gnommer.    

Thanks for the updated screenshot.    We're looking into the missing report issue, and will get back to you soon.

For the duplicate entries, I'll look into more to see what's going on there.

**Comment by mister-gnommer** [comment] 2020-12-03 07:55
Ok, please let me know if I can be of any help.

**Comment by mmclead** [comment] 2020-12-05 04:56
We pushed a fix yesterday for the project reports.  

Can you try again and let me know if it's resolved for you?

**Comment by mister-gnommer** [comment] 2020-12-05 22:44
We are almost there. Project are still multiplied as on last screen shot, but I am able to generate report when choosing right project. I mean that if I select right project from 4 "clipERP3" projects (there are actually 5 now) I get proper report, others still return "No data available"

**Comment by mmclead** [comment] 2020-12-07 19:29
Alright, we are getting there.    The multiples of the projects in the list is interesting.  We actually hash using Blake2b any sensitive info, like project names or git repos before it gets sent to us so, I'll have to do a little bit of digging to uncover the issue here.  But, I have an idea and will update you soon.  

Thanks for helping to work all this out with us.

**Comment by mister-gnommer** [comment] 2020-12-07 22:51
Let me know if I can provide you any helpful information. This aren't any top-secret projects, I can invite you as collaborator if this helps.

**Comment by mmclead** [comment] 2021-02-09 18:50
Hi @mister-gnommer , we haven't forgotten about this.    We've updated a couple things to reduce the duplicates, but there is still a part of the aggregations of stats per project that is causing some duplicate names to show up.    

Right now this is due to git repo names, project names, and root directory names being the same and particular datatypes getting segmented into each one of those.     For now, selecting the all copies of each project name and running the report will give you accurate metrics, and we are working on fixing the underlying aggregation issue.

**Comment by nicolascalev** [comment] 2021-04-05 01:32
### Description

Hi! I hope you all are doing great, I just want to report the same issue.

I just installed this extension it looks super nice, my projects aren't loading tho, since I installed it I have accumulated 44 m coding, but both my web dahsboard and project listing are empty.

In case this helps, I created my account with GitHub.

**VSCode**
![image](https://user-images.githubusercontent.com/33049057/113527718-a19eff80-957b-11eb-8781-7ce399b48c53.png)

**Web App**
![image](https://user-images.githubusercontent.com/33049057/113527774-cdba8080-957b-11eb-80ab-d0e75e275076.png)

### Desktop

- Windows 10 Home
- Plugin version v2.5.11
- VSCode v1.55.0

**Comment by mmclead** [comment] 2021-04-05 02:30
Hi @nicolascalev thanks for using the extension.  

For the web app and the projects listing we aggregate the data once a day. So you'll see it tomorrow. 

But inside the editor you can see the up to date metrics by clicking on the Dashboard link in the side bar.

**Comment by nicolascalev** [comment] 2021-04-05 03:51
> Hi @nicolascalev thanks for using the extension.  
> 
> For the web app and the projects listing we aggregate the data once a day. So you'll see it tomorrow. 
> 
> But inside the editor you can see the up to date metrics by clicking on the Dashboard link in the side bar.  
> 
> 

Thanks for your fast response @mmclead sounds good, I'll check tomorrow then🙌🏽

**Comment by mmclead** [comment] 2021-07-06 23:15
This issue has been resolved with our new features!

**Closed** 2021-07-06 23:15 UTC
Labels: bug
